# netflix-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-deployment
spec:
  selector:
    matchLabels:
      app: netflix
  replicas: 3
  template:
    metadata:
      labels:
        app: netflix
    spec:
      containers:
      - name: netflix
        image: netflix/eureka-server:latest
        ports:
        - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: netflix-service
spec:
  selector:
    app: netflix
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: LoadBalancer