#touch ansible/playbooks/applications/update-services.yaml
---
- name: Update Services
  hosts: all
  become: true
  tasks:
    - name: Update Apt package cache
      apt:
        update_cache: yes

    - name: Upgrade packages
      apt:
        upgrade: 'yes'
        autoremove: 'yes'
        autoclean: 'yes'

    - name: Restart services
      ansible.builtin.service:
        name: "{{ item }}"
        state: restarted
      loop:
        - apache2
        - nginx
        - mysql
        - postgresql
        - memcached
        - rabbitmq-server
        - elasticsearch
        - kibana
        - logstash
        - beanstalkd
        - cron
        - syslog
        - ntp